steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - '--no-cache'
          - '-t'
          - >-
              $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - .
          - '-f'
          - Dockerfile
      id: Build
    - name: gcr.io/cloud-builders/docker
      args:
          - push
          - >-
              $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      id: Push
    - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
      args:
          - run
          - services
          - update
          - $_SERVICE_NAME
          - '--platform=managed'
          - >-
              --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - >-
              --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
          - '--region=$_DEPLOY_REGION'
          - '--quiet'
      id: Deploy
      entrypoint: gcloud
images:
    - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
    substitutionOption: ALLOW_LOOSE
    logging: CLOUD_LOGGING_ONLY
substitutions:
    _AR_HOSTNAME: asia-east1-docker.pkg.dev
    _AR_REPOSITORY: cloud-run-source-deploy
    _AR_PROJECT_ID: gen-lang-client-0017766570
    _PLATFORM: managed
    _SERVICE_NAME: vibe-calculator
    _TRIGGER_ID: 8eb32000-6551-49bb-96bf-7917cf610761
    _DEPLOY_REGION: asia-east1
tags:
    - gcp-cloud-build-deploy-cloud-run
    - gcp-cloud-build-deploy-cloud-run-managed
    - vibe-calculator
